window.DATASETS = window.DATASETS || {};
window.DATASETS.geography = [
  { q:"What is geography?", a:"Geography studies Earth’s places, environments, and the relationships between people and their surroundings." },
  { q:"What are the two main branches of geography?", a:"Physical geography and human geography." },
  { q:"What is physical geography?", a:"It studies natural features and processes like landforms, climate, soils, water, and ecosystems." },
  { q:"What is human geography?", a:"It studies human activities and patterns like population, settlements, culture, economy, and urbanization." },
  { q:"What is latitude?", a:"Latitude is the angular distance north or south of the equator, measured in degrees." },
  { q:"What is longitude?", a:"Longitude is the angular distance east or west of the Prime Meridian, measured in degrees." },
  { q:"What is the Prime Meridian?", a:"0° longitude line passing through Greenwich, used as a reference for east/west longitudes." },
  { q:"What is the equator?", a:"0° latitude line dividing Earth into Northern and Southern Hemispheres." },
  { q:"What are time zones based on?", a:"Mainly on longitude and Earth’s rotation (about 15° longitude per hour)." },
  { q:"What is a map projection?", a:"A method to represent Earth’s curved surface on a flat map, always causing some distortion." },
  { q:"What is scale on a map?", a:"The ratio between distance on the map and actual ground distance." },
  { q:"What is a contour line?", a:"A line on a map joining points of equal elevation." },
  { q:"What is a watershed?", a:"An area of land that drains all water to a common outlet like a river or lake." },
  { q:"What is a drainage basin?", a:"Another term for watershed/catchment: the land area drained by a river and its tributaries." },
  { q:"What is erosion?", a:"The wearing away and transport of soil/rock by water, wind, ice, or gravity." },
  { q:"What is weathering?", a:"The breakdown of rocks in place by physical, chemical, or biological processes." },
  { q:"What is mass wasting?", a:"Downslope movement of soil/rock due to gravity, such as landslides." },
  { q:"What is a delta?", a:"A depositional landform at a river mouth where sediments build out into a sea or lake." },
  { q:"What is a floodplain?", a:"A flat area near a river, formed by deposits during floods, usually fertile." },
  { q:"What is a meander?", a:"A curved bend in a river channel formed by lateral erosion and deposition." },
  { q:"What is an oxbow lake?", a:"A U-shaped lake formed when a river meander is cut off from the main channel." },
  { q:"What is a glacier?", a:"A large moving mass of ice formed from compacted snow over long periods." },
  { q:"What is a moraine?", a:"Rock debris deposited by glaciers, often forming ridges." },
  { q:"What is plate tectonics?", a:"The theory that Earth’s lithosphere is divided into plates that move and interact, creating earthquakes, volcanoes, and mountains." },
  { q:"What is a fault?", a:"A crack in Earth’s crust where movement has occurred." },
  { q:"What is an earthquake?", a:"Shaking of the ground caused by sudden release of energy along faults or plate boundaries." },
  { q:"What is a volcano?", a:"An opening where magma, gases, and ash can erupt to the surface." },
  { q:"What is an igneous rock?", a:"Rock formed by cooling and solidification of magma or lava." },
  { q:"What is a sedimentary rock?", a:"Rock formed from deposited sediments compacted and cemented over time." },
  { q:"What is a metamorphic rock?", a:"Rock changed by heat, pressure, or fluids without melting." },
  { q:"What is the lithosphere?", a:"The rigid outer layer of Earth (crust + uppermost mantle)." },
  { q:"What is the hydrosphere?", a:"All water on Earth: oceans, rivers, lakes, groundwater, and ice." },
  { q:"What is the biosphere?", a:"All living organisms and ecosystems on Earth." },
  { q:"What is the atmosphere?", a:"The envelope of gases surrounding Earth." },
  { q:"What is population density?", a:"Number of people per unit area, often per square kilometer." },
  { q:"What is urbanization?", a:"Growth of the urban population and expansion of cities." },
  { q:"What is migration?", a:"Movement of people from one place to another, temporary or permanent." },
  { q:"What is a renewable resource?", a:"A resource that replenishes naturally on human timescales (e.g., solar, wind, biomass)." },
  { q:"What is a non-renewable resource?", a:"A resource that forms very slowly (e.g., coal, petroleum, natural gas)." },
  { q:"What is sustainable development?", a:"Development that meets present needs without harming the ability of future generations to meet theirs." },
  { q:"What is biodiversity?", a:"Variety of life at genetic, species, and ecosystem levels." },
  { q:"What is deforestation?", a:"Large-scale removal of forest cover, often leading to habitat loss and soil erosion." },
  { q:"What is desertification?", a:"Land degradation in dry areas due to climate variation and human activities." },
  { q:"What is a cyclone?", a:"A rotating low-pressure system; tropical cyclones form over warm oceans." },
  { q:"What is GIS?", a:"Geographic Information System: tools to store, analyze, and visualize spatial data." },
  { q:"What is remote sensing?", a:"Collecting information about Earth from satellites/aircraft without direct contact." },
  { q:"What is a developed country?", a:"A country with high income, strong infrastructure, and high human development indicators." },
  { q:"What is a developing country?", a:"A country with lower average income and developing infrastructure and human development indicators." },
  { q:"What is globalization?", a:"Increasing worldwide connections in trade, culture, technology, and movement of people and ideas." }
];
